# Build customization
builds:
 - main: main.go
   binary: aggregate-api
   goos:
     - windows
     - darwin
     - linux
   goarch:
     - amd64
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
  files:
    - LICENSE